<div class="hero-unit">
    <h1>Welcome to <span class="zf-green">Zend Framework 2</span> on <span style="color:#0266C8">Google AppEngine</span></h1>
    <p>This is a vanilla ZF2 skeleton-app running on Google AppEngine with minimal changes. All code behind this is available on Github.
</div>

<div class="row">

    <div class="span4">
        <h2>Testing routes</h2>
        <p>Testing a simple route with AppEngine (to /appenginetest).</p>
        <p><a class="btn btn-success" href="/appenginetest">AppEngine Test</a></p>
    </div>

    <div class="span4">
        <h2>Test local file storage</h2>
        <p>Try to write the current date to a local file and read the value from it.</p>
        <p><a class="btn btn-success" href="/localstoragetest">Test local storage &raquo;</a></p>
   </div>

   <div class="span4">
       <h2>Fork on Github</h2>
       <p>The (very small) code that runs this project is avialabe on Github.</p>
       <p><a class="btn btn-success" href="https://github.com/tommienu/zf2appengine" target="_blank">Fork On Github! &raquo;</a></p>
   </div>
</div>
