<div class="hero-unit">
    <h1>Welcome to <span class="zf-green">Zend Framework 2</span> on <span style="color:#0266C8">Google AppEngine</span></h1>
</div>

<div class="row">

    <div class="span4">
        <h2>Testing routes</h2>
        <p>Testing a simple route with AppEngine (to /appenginetest).</p>
        <p><a class="btn btn-success" href="/appenginetest" target="_blank">AppEngine Test</a></p>
    </div>

    <div class="span4">
        <h2>Test local file storage</h2>
        <p>Try to write the current date to a local file and read the value from it.</p>
        <p><a class="btn btn-success" href="/localstoragetest" target="_blank">Test local storage &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
   </div>
</div>
